apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationgroups.k8s.humalecttest.io
spec:
  group: k8s.humalecttest.io
  names:
    kind: ApplicationGroup
    plural: applicationgroups
    singular: applicationgroup
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
             spec:
               type: object
               properties:
                 applicationName:
                   type: string
                 domain:
                   type: string
                 replicas:
                   type: integer
                   minimum: 1
