apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-02
  template:
    metadata:
      labels:
        app: app-02
    spec:
      containers:
      - name: app-02
        image: app-02:latest
        ports:
        - containerPort: 5000
