apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-01-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-01-app
  template:
    metadata:
      labels:
        app: app-01-app
    spec:
      containers:
      - name: app-01r-app
        image: app-01-app:latest
        ports:
        - containerPort: 5000
